name: Terraform Code folders test

on: [push]

jobs:
  ap-south-1_region:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.3"

      - name: Navigate to specific folder
        run: cd non-prod/dev/ap-south-1/
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: list directories
        run: |
            echo $(ls -l)
            ls -l

  us-east-1_region:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.3"

      - name: Navigate to specific folder
        run: cd prod/staging/us-east-1/
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: list directories
        run: |
            echo $(ls -l)
            ls -l
