name: Terraform Code folders test

on: [push]

jobs:
  ap-south-1_region:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash
            working-directory: non-prod/dev/ap-south-1/

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.3"

      # - name: creating file
      #   working-directory: non-prod/dev/ap-south-1/
      #   run: touch file1.txt
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: list directories
        run: |
            ls -l
            pwd

  us-east-1_region:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash
            working-directory: prod/staging/us-east-1/

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.3"

      # - name: creating file
      #   working-directory: prod/staging/us-east-1/
      #   run: touch file2.txt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: list directories
        run: |
            ls -l
            pwd
